# ─── Gradle JVM settings ────────────────────────────────────────────────────
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# ─── AndroidX ───────────────────────────────────────────────────────────────
android.useAndroidX=true

# ─── Parallel execution ──────────────────────────────────────────────────────
org.gradle.parallel=true

# ─── Gradle daemon ───────────────────────────────────────────────────────────
org.gradle.daemon=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
